### ISSUE TITLE
Hello, I am also interested in it.

### ISSUE THREAD

**Issue by McDull1Q84** [micmelesse/thesis#1]
Hi, sorry to bother you, I am also interested in using deep learning to do 3D-reconstruction works, recently I am reading the code wrote by Christophe, but I am not familiar with theano, then I saw you guys rebuilt it with tensorflow which I am more familiar with, so have you finished it yet?  May you have a good  day!

**Comment by micmelesse** [comment]
Hi Tony1Q84,
Yes, the implementation is more or less complete. Let me know if I can help with anything.

**Comment by McDull1Q84** [comment]
Thank you so much for your reply，I am so happy that I can learn this work easier. So could you please write a synopsis or something like that about how to use the code, maybe about the environment you use or something else. Thanks one more time!

**Comment by micmelesse** [comment]
I have expanded the README a bit more but the thesis goes in much more depth. I am going to close this issue for now but if you experience any other problems feel free to either open another issue or email me at micmelesse@gmail.com.

**Comment by McDull1Q84** [comment]
OK， thanks so much!
