### ISSUE TITLE
How is the performance?

### ISSUE THREAD

**Issue by yindaz** [micmelesse/thesis#5]
Hi,

I found this while I was looking for a tensorflow implementation of the 3DR2N2. This implementation looks very cool, and code is easy to follow. I just wonder how is the performance compared to the release from the 3DR2N2 author.

Also, would you like to share several pre-trained snapshots? That would be also greatly useful. Thanks!

**Comment by micmelesse** [comment]
It performs about the same as the original implementation. You can find the results in the write up. I am sorry but I did not keep any of the pre-trained weights. I will try and upload one in the next few weeks.

**Comment by yindaz** [comment]
Sounds great! Looking forward to it. Thanks in advance!
