### ISSUE TITLE
ImportError: No module named lib

### ISSUE THREAD

**Issue by ihmc3jn09hk** [micmelesse/thesis#7]
There is some problem for the instruction.
The helper script "setup_dir.sh" doesn't work.
When running it accordingly, it returns
`
File "<string>", line 4, in <module>
ImportError: No module named lib
`

**Comment by micmelesse** [comment]
Sorry for not responding sooner. I have updated the scripts and the instructions. I will close the issue but feel free to reopen it if you encounter issues.
